GET /users HTTP/1.1
Host: localhost:8888

###
POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "1234"
}

###
GET /users/admin@mail.com HTTP/1.1
Host: localhost:8888